[build]
  functions = "netlify/functions"

[functions]
  external_node_modules = ["resend"]   # bundle the email SDK

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
