# Tell Netlify where to find static files and functions
[build]
  publish   = "."
  functions = "netlify/functions"

# Always bundle functions with esbuild (works with ESM)
[functions]
  node_bundler = "esbuild"

# Dev/prod redirect: /api/* → /.netlify/functions/*
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
